{application,opentelemetry_exporter,
             [{description,"OpenTelemetry Protocol Exporter"},
              {vsn,"1.0.4"},
              {registered,[]},
              {applications,[kernel,stdlib,inets,grpcbox,
                             tls_certificate_check,opentelemetry_api]},
              {env,[]},
              {modules,[opentelemetry_exporter,
                        opentelemetry_exporter_trace_service_pb,
                        opentelemetry_trace_service]},
              {doc,"doc"},
              {licenses,["Apache-2.0"]},
              {links,[{"GitHub",
                       "https://github.com/open-telemetry/opentelemetry-erlang"}]}]}.
